import { tanstackRouter } from "@tanstack/router-plugin/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

// https://vite.dev/config/
export default defineConfig({
  base: process.env.VITE_BASE_PATH || "/",
  plugins: [
    tanstackRouter({
      target: "react",
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      virtualRouteConfig: "./src/app/routes.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: ["// biome-ignore-all lint: generated by TanStack Router"],
    }),
    react(),
  ],
  resolve: {
    alias: {
      "@": "/src",
    },
    // client-kit 以本地路径依赖接入（ADR-16）：按 node_modules 里的链接路径解析，共用包
    // 里的 react 与本项目是同一份；dedupe 兜底，任何路径都只打包一份 React
    preserveSymlinks: true,
    dedupe: ["react", "react-dom"],
  },
  server: {
    port: parseInt(process.env.VITE_PORT || "5173", 10),
    strictPort: true,
  },
});
