// Generated from web/packages/platform/src/i18n.ts by tools/gen-platform-i18n.py.
// Do not edit this file. The ReasonCode enum comes from contracts/.
import 'dart:io' show Platform;

import '../contracts/contracts.dart';

String kailoReasonText(ReasonCode reason, {String? locale}) {
  final language = (locale ?? Platform.localeName).toLowerCase();
  if (language.startsWith('zh')) {
    return switch (reason) {
      ReasonCode.ADMISSION_ABANDONED => '请求在判定完成前已被放弃。',
      ReasonCode.APPROVAL_CONSUME_WINDOW_CLOSED => '审批未在时限内使用。',
      ReasonCode.APPROVAL_DENIED => '审批人拒绝了请求。',
      ReasonCode.APPROVAL_EXPIRED => '审批在决定前已过期。',
      ReasonCode.APPROVAL_INVALIDATED => '事实或权限已变化，审批不再有效。',
      ReasonCode.APPROVAL_NOT_OPEN => '该审批已不再接受决定。',
      ReasonCode.APPROVAL_SELECTOR_UNRESOLVABLE => '找不到可以审批此请求的人。',
      ReasonCode.APPROVAL_WITHDRAWN => '请求已被撤回。',
      ReasonCode.APPROVER_NOT_ELIGIBLE => '你不具备审批此请求的资格。',
      ReasonCode.CAPABILITY_BLOCKED => '该能力尚未开放。',
      ReasonCode.CLIENT_KEY_ALREADY_BOUND => '这把设备密钥已被撤销或属于他人。',
      ReasonCode.CLIENT_KEY_LIMIT_REACHED => '你登记的设备已达上限，请先撤销一台。',
      ReasonCode.CLIENT_KEY_NOT_FOUND => '该设备未登记在你名下。',
      ReasonCode.CLIENT_KEY_PROOF_INVALID => 'Kailo 未接受本机的密钥证明。',
      ReasonCode.DEPENDENCY_UNAVAILABLE => '所依赖的服务暂不可用。',
      ReasonCode.DISPATCH_RESULT_UNKNOWN => '是否已生效尚不明确。',
      ReasonCode.DUPLICATE_DECISION => '你已记录了不同的决定，决定不能更改。',
      ReasonCode.EXTERNAL_RESULT_UNKNOWN => '结果尚不明确，正在对账。',
      ReasonCode.IDEMPOTENCY_KEY_REUSED => '同一请求此前已以不同内容提交过。',
      ReasonCode.IDENTITY_HEADER_MISSING => 'Kailo 无法识别这个账号。',
      ReasonCode.IDENTITY_UNKNOWN => 'Kailo 无法识别这个账号。',
      ReasonCode.INVALID_PARAMETERS => '请求不完整或格式不正确。',
      ReasonCode.INVITATION_ALREADY_REDEEMED => '邀请已被使用。',
      ReasonCode.INVITATION_EXPIRED => '邀请已过期，请向邀请人索取新的邀请。',
      ReasonCode.INVITATION_NOT_FOUND => '邀请链接无效，请确认复制完整。',
      ReasonCode.INVITATION_REVOKED => '邀请已被撤回，请向邀请人索取新的邀请。',
      ReasonCode.INVITEE_ALREADY_MEMBER => '你已经是该组织的成员。',
      ReasonCode.LAST_TENANT_ADMIN => '这会让组织失去最后一位管理员。',
      ReasonCode.NATIVE_SURFACE_REQUIRED =>
        '这一步只能在 Kailo Desktop 或 Mobile 上完成。',
      ReasonCode.PERMISSION_DENIED => '你没有执行此操作的权限。',
      ReasonCode.PROJECTION_DELAYED => '显示的状态可能尚未更新。',
      ReasonCode.PUBLISH_REJECTED => '消息被拒绝。',
      ReasonCode.PUBLISH_RESULT_UNKNOWN => '消息是否送达尚不明确。',
      ReasonCode.SCOPE_GUARD_FAILED => '超出了你所属的组织或工作区范围。',
      ReasonCode.SELF_APPROVAL_DENIED => '不能审批自己发起的请求。',
      ReasonCode.SESSION_NOT_ACTIVE => '你的 Kailo 会话已失效。',
      ReasonCode.SURFACE_CAPABILITY_UNAVAILABLE =>
        '此处不提供该功能，请在 Kailo Web 或 Desktop 上继续。',
      ReasonCode.TARGET_NOT_FOUND => '对象已不存在，或你无权查看。',
      ReasonCode.TARGET_STATE_CONFLICT => '对象当前的状态不允许此操作。',
      ReasonCode.TENANT_MEMBERSHIP_NOT_ACTIVE => '你在该组织的成员资格未生效。',
      ReasonCode.TENANT_SELECTION_NOT_AVAILABLE => '你的账号属于多个组织，目前还不能在其间选择。',
      ReasonCode.WAITING_APPROVAL => '正在等待审批。',
    };
  }
  return switch (reason) {
    ReasonCode.ADMISSION_ABANDONED =>
      'The request was abandoned before it could be evaluated.',
    ReasonCode.APPROVAL_CONSUME_WINDOW_CLOSED =>
      'The approval was not used in time.',
    ReasonCode.APPROVAL_DENIED => 'An approver denied it.',
    ReasonCode.APPROVAL_EXPIRED =>
      'The approval expired before it was decided.',
    ReasonCode.APPROVAL_INVALIDATED =>
      'The approval is no longer valid because the facts or permissions changed.',
    ReasonCode.APPROVAL_NOT_OPEN =>
      'This approval is no longer taking decisions.',
    ReasonCode.APPROVAL_SELECTOR_UNRESOLVABLE =>
      'No one can be asked to approve this.',
    ReasonCode.APPROVAL_WITHDRAWN => 'The request was withdrawn.',
    ReasonCode.APPROVER_NOT_ELIGIBLE =>
      'You are not eligible to decide on this approval.',
    ReasonCode.CAPABILITY_BLOCKED => 'This capability is not available.',
    ReasonCode.CLIENT_KEY_ALREADY_BOUND =>
      'This device key was revoked or belongs to someone else.',
    ReasonCode.CLIENT_KEY_LIMIT_REACHED =>
      'You have registered the maximum number of devices. Revoke one first.',
    ReasonCode.CLIENT_KEY_NOT_FOUND => 'That device is not registered to you.',
    ReasonCode.CLIENT_KEY_PROOF_INVALID =>
      'Kailo did not accept this device\'s key proof.',
    ReasonCode.DEPENDENCY_UNAVAILABLE =>
      'A service this depends on is unavailable.',
    ReasonCode.DISPATCH_RESULT_UNKNOWN =>
      'Whether it took effect is not known yet.',
    ReasonCode.DUPLICATE_DECISION =>
      'You already recorded a different decision, which cannot be changed.',
    ReasonCode.EXTERNAL_RESULT_UNKNOWN =>
      'The outcome is not known yet; it is being reconciled.',
    ReasonCode.IDEMPOTENCY_KEY_REUSED =>
      'This request was already sent with different details.',
    ReasonCode.IDENTITY_HEADER_MISSING =>
      'Kailo does not recognize this account.',
    ReasonCode.IDENTITY_UNKNOWN => 'Kailo does not recognize this account.',
    ReasonCode.INVALID_PARAMETERS => 'The request was incomplete or malformed.',
    ReasonCode.INVITATION_ALREADY_REDEEMED =>
      'This invitation has already been used.',
    ReasonCode.INVITATION_EXPIRED =>
      'This invitation has expired. Ask for a new one.',
    ReasonCode.INVITATION_NOT_FOUND =>
      'This invitation link is not valid. Check that you copied all of it.',
    ReasonCode.INVITATION_REVOKED =>
      'This invitation was withdrawn. Ask for a new one.',
    ReasonCode.INVITEE_ALREADY_MEMBER =>
      'You are already a member of this organization.',
    ReasonCode.LAST_TENANT_ADMIN =>
      'The organization would be left without an admin.',
    ReasonCode.NATIVE_SURFACE_REQUIRED =>
      'This must be done in Kailo Desktop or Mobile.',
    ReasonCode.PERMISSION_DENIED => 'You do not have permission to do this.',
    ReasonCode.PROJECTION_DELAYED => 'The status shown may be out of date.',
    ReasonCode.PUBLISH_REJECTED => 'The message was rejected.',
    ReasonCode.PUBLISH_RESULT_UNKNOWN =>
      'Whether the message was delivered is not known yet.',
    ReasonCode.SCOPE_GUARD_FAILED =>
      'This is outside the organization or workspace you belong to.',
    ReasonCode.SELF_APPROVAL_DENIED => 'You cannot approve your own request.',
    ReasonCode.SESSION_NOT_ACTIVE => 'Your Kailo session is no longer active.',
    ReasonCode.SURFACE_CAPABILITY_UNAVAILABLE =>
      'This is not available here. Continue in Kailo on the web or desktop.',
    ReasonCode.TARGET_NOT_FOUND => 'It no longer exists, or you cannot see it.',
    ReasonCode.TARGET_STATE_CONFLICT =>
      'Its current state does not allow this.',
    ReasonCode.TENANT_MEMBERSHIP_NOT_ACTIVE =>
      'Your membership in this organization is not active.',
    ReasonCode.TENANT_SELECTION_NOT_AVAILABLE =>
      'Your account belongs to more than one organization, which cannot be chosen between yet.',
    ReasonCode.WAITING_APPROVAL => 'Waiting for approval.',
  };
}

String kailoReasonCode(ReasonCode reason) => reasonCodeValues.reverse[reason]!;
