import { tanstackRouter } from "@tanstack/router-plugin/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import { profileAssets } from "../../client-kit/ts/platform/profile-assets.ts";

// https://vite.dev/config/
export default defineConfig({
  base: process.env.VITE_BASE_PATH || "/",
  plugins: [
    profileAssets(import.meta.url),
    {
      name: "deployed-platform-build-info",
      apply: "build",
      generateBundle() {
        const buildId = process.env.PLATFORM_BUILD_ID;
        if (!buildId || !/^sha256:[a-f0-9]{64}$/.test(buildId)) {
          this.error("PLATFORM_BUILD_ID must come from the original source manifest");
        }
        this.emitFile({
          type: "asset", fileName: "platform-build-info.json",
          source: JSON.stringify({
            subject: "BUZZ_WEB", buildId, hostApiVersion: "NONE",
            adapterProtocolVersions: [], driverRegistryKeys: [], platformPortKeys: [],
            reportedAt: new Date().toISOString(),
          }),
        });
      },
    },
    tanstackRouter({
      target: "react",
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      virtualRouteConfig: "./src/app/routes.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: ["// biome-ignore-all lint: generated by TanStack Router"],
    }),
    react(),
  ],
  resolve: {
    alias: {
      "@": "/src",
    },
  },
  server: {
    port: parseInt(process.env.VITE_PORT || "5173", 10),
    strictPort: true,
  },
});
