// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as settingsRouteImport } from "./routes/settings";
import { Route as indexRouteImport } from "./routes/index";
import { Route as platformDotsectionRouteImport } from "./routes/platform.$section";
import { Route as messagesDotnewRouteImport } from "./routes/messages.new";
import { Route as channelsDotchannelIdRouteImport } from "./routes/channels.$channelId";

const settingsRoute = settingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const platformDotsectionRoute = platformDotsectionRouteImport.update({
  id: "/platform/$section",
  path: "/platform/$section",
  getParentRoute: () => rootRouteImport,
} as any);
const messagesDotnewRoute = messagesDotnewRouteImport.update({
  id: "/messages/new",
  path: "/messages/new",
  getParentRoute: () => rootRouteImport,
} as any);
const channelsDotchannelIdRoute = channelsDotchannelIdRouteImport.update({
  id: "/channels/$channelId",
  path: "/channels/$channelId",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/settings": typeof settingsRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/platform/$section": typeof platformDotsectionRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/settings": typeof settingsRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/platform/$section": typeof platformDotsectionRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/settings": typeof settingsRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/platform/$section": typeof platformDotsectionRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/settings"
    | "/channels/$channelId"
    | "/messages/new"
    | "/platform/$section";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/settings"
    | "/channels/$channelId"
    | "/messages/new"
    | "/platform/$section";
  id:
    | "__root__"
    | "/"
    | "/settings"
    | "/channels/$channelId"
    | "/messages/new"
    | "/platform/$section";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  settingsRoute: typeof settingsRoute;
  channelsDotchannelIdRoute: typeof channelsDotchannelIdRoute;
  messagesDotnewRoute: typeof messagesDotnewRoute;
  platformDotsectionRoute: typeof platformDotsectionRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof settingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/platform/$section": {
      id: "/platform/$section";
      path: "/platform/$section";
      fullPath: "/platform/$section";
      preLoaderRoute: typeof platformDotsectionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/messages/new": {
      id: "/messages/new";
      path: "/messages/new";
      fullPath: "/messages/new";
      preLoaderRoute: typeof messagesDotnewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/channels/$channelId": {
      id: "/channels/$channelId";
      path: "/channels/$channelId";
      fullPath: "/channels/$channelId";
      preLoaderRoute: typeof channelsDotchannelIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  settingsRoute: settingsRoute,
  channelsDotchannelIdRoute: channelsDotchannelIdRoute,
  messagesDotnewRoute: messagesDotnewRoute,
  platformDotsectionRoute: platformDotsectionRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
