#!/usr/bin/env python3
"""Project the shared TypeScript reason catalog into Mobile's Dart surface."""

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "web/packages/platform/src/i18n.ts"
TS_ENUM = ROOT / "web/packages/contracts/src/generated/contracts.ts"
DART_ENUM = ROOT / "mobile/lib/shared/contracts/generated/contracts.dart"
TARGET = ROOT / "mobile/lib/shared/kailo/kailo_reason_text.dart"


def block(source: str, start: str, end: str) -> str:
    match = re.search(re.escape(start) + r"(.*?)" + re.escape(end), source, re.S)
    if match is None:
        raise ValueError(f"source block not found: {start}")
    return match.group(1)


def catalog() -> list[tuple[str, str, str]]:
    ts_enum = block(TS_ENUM.read_text(), "export enum ReasonCode {", "}\n")
    names = dict(re.findall(r'\b(\w+)\s*=\s*"([A-Z_]+)"\s*,', ts_enum))
    dart_enum = block(DART_ENUM.read_text(), "enum ReasonCode {", "}\n")
    dart_names = set(re.findall(r"\b([A-Z_]+)\s*,", dart_enum))
    if not names or set(names.values()) != dart_names:
        raise ValueError("TypeScript and Dart ReasonCode enums differ")

    body = block(
        SOURCE.read_text(),
        "export const reasonMessages = {",
        "} as const satisfies Record<ReasonCode, Message>;",
    )
    entry = re.compile(
        r'\[ReasonCode\.(\w+)\]:\s*\{\s*en:\s*("(?:\\.|[^"\\])*"),'
        r'\s*"zh-CN":\s*("(?:\\.|[^"\\])*"),?\s*\},',
        re.S,
    )
    found = entry.findall(body)
    if entry.sub("", body).strip() or len(found) != len(names):
        raise ValueError("reasonMessages contains an unrecognized or missing entry")
    messages = {name: (json.loads(en), json.loads(zh)) for name, en, zh in found}
    if set(messages) != set(names):
        raise ValueError("reasonMessages does not cover exactly the ReasonCode enum")
    return [(code, *messages[name]) for name, code in names.items()]


def dart_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$")
    return "'" + escaped.replace("\n", "\\n") + "'"


def render(rows: list[tuple[str, str, str]]) -> str:
    lines = [
        "// Generated from web/packages/platform/src/i18n.ts by tools/gen-platform-i18n.py.",
        "// Do not edit this file. The ReasonCode enum comes from contracts/.",
        "import 'dart:io' show Platform;",
        "",
        "import '../contracts/contracts.dart';",
        "",
        "String kailoReasonText(ReasonCode reason, {String? locale}) {",
        "  final language = (locale ?? Platform.localeName)",
        "      .toLowerCase();",
        "  if (language.startsWith('zh')) {",
        "    return switch (reason) {",
    ]
    lines.extend(f"      ReasonCode.{code} => {dart_string(zh)}," for code, _, zh in rows)
    lines.extend(["    };", "  }", "  return switch (reason) {"])
    lines.extend(f"    ReasonCode.{code} => {dart_string(en)}," for code, en, _ in rows)
    lines.extend(
        [
            "  };",
            "}",
            "",
            "String kailoReasonCode(ReasonCode reason) => reasonCodeValues.reverse[reason]!;",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    with tempfile.TemporaryDirectory() as directory:
        temporary = Path(directory) / TARGET.name
        temporary.write_text(render(catalog()))
        dart = shutil.which("dart")
        if dart is None:
            raise ValueError("Dart formatter unavailable")
        subprocess.run([dart, "format", str(temporary)], check=True, capture_output=True)
        generated = temporary.read_text()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != generated:
            print(f"FAIL: {TARGET.relative_to(ROOT)} is out of sync", file=sys.stderr)
            return 1
        print("PASS: Mobile reason catalog matches the shared TypeScript source")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(generated)
    print(f"Generated {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (ValueError, subprocess.CalledProcessError) as error:
        print(f"FAIL: {error}", file=sys.stderr)
        sys.exit(1)
