import { defineConfig, devices } from "@playwright/test";

// The static server's port and directory; override to run several builds side by side.
const port = process.env.BUZZ_E2E_PORT ?? "4173";

export default defineConfig({
  testDir: "./tests/e2e",
  timeout: 30_000,
  retries: process.env.CI ? 2 : 0,
  workers: 1,
  reporter: [
    ["list"],
    ["html", { open: "never", outputFolder: "playwright-report" }],
  ],
  use: {
    baseURL: `http://127.0.0.1:${port}`,
    screenshot: "only-on-failure",
    trace: "on-first-retry",
    video: "retain-on-failure",
  },
  projects: [
    {
      name: "smoke",
      testMatch: [
        "**/smoke.spec.ts",
        "**/device-key.spec.ts",
        "**/kailo-bootstrap.spec.ts",
        "**/kailo-platform.spec.ts",
        "**/tooltip-semantics.spec.ts",
        "**/navigation.spec.ts",
        "**/channels.spec.ts",
        "**/channel-shared-header-backdrop.spec.ts",
        "**/auxiliary-pane-close-visibility.spec.ts",
        "**/channel-composer-overflow.spec.ts",
        "**/badge.spec.ts",
        "**/messaging.spec.ts",
        "**/message-feedback-snapshots.spec.ts",
        "**/message-copy-link.spec.ts",
        "**/channel-mute.spec.ts",
        "**/channel-star.spec.ts",
        "**/channel-activity-popover.spec.ts",
        "**/pubkey-display-screenshots.spec.ts",
        "**/file-attachment.spec.ts",
        "**/image-attachment-gallery.spec.ts",
        "**/composer-image-draw.spec.ts",
        "**/video-attachment.spec.ts",
        "**/spoiler.spec.ts",
        "**/composer-link-shortcut.spec.ts",
        "**/composer-selection-formatting.spec.ts",
        "**/composer-tooltip-dismiss.spec.ts",
        "**/mentions.spec.ts",
        "**/mention-spacing.spec.ts",
        "**/mention-clipboard.spec.ts",
        "**/mention-recipients.spec.ts",
        "**/relay-reconnect.spec.ts",
        "**/relay-reconnect-affordance.spec.ts",
        "**/relay-connectivity.spec.ts",
        "**/unread-pill.spec.ts",
        "**/sidebar-more-unread-overlap.spec.ts",
        "**/sidebar-snapshot.spec.ts",
        "**/home-collapsed-top-chrome.spec.ts",
        "**/top-chrome-zoom-clearance.spec.ts",
        "**/thread-unread.spec.ts",
        "**/thread-load-failure.spec.ts",
        "**/boot-splash.spec.ts",
        "**/thread-reply-anchor-roleplay.spec.ts",
        "**/threadpane-ultrawide.spec.ts",
        "**/thread-focus-mode.spec.ts",
        "**/virtualization.spec.ts",
        "**/scroll-history.spec.ts",
        "**/channel-dense-second-reach.spec.ts",
        "**/channel-window-mock-paging.spec.ts",
        "**/channel-head-restart.spec.ts",
        "**/live-broadcast-reply-timeline.spec.ts",
        "**/markdown-parse-cache.spec.ts",
        "**/markdown-tables.spec.ts",
        "**/overscroll-boundary.spec.ts",
        "**/cold-switch-longtask.perf.ts",
        "**/timeline-no-shift.spec.ts",
        "**/drafts-screenshots.spec.ts",
        "**/drafts-all-fix-screenshots.spec.ts",
        "**/inbox-refactor-screenshots.spec.ts",
        "**/inbox-title-overlap.spec.ts",
        "**/message-author-overlap.spec.ts",
        "**/buzz-theme-screenshots.spec.ts",
        "**/appearance-previews.spec.ts",
        "**/channel-sort.spec.ts",
        "**/inbox-live-update.spec.ts",
      ],
      use: {
        ...devices["Desktop Chrome"],
      },
    },
    {
      name: "integration",
      testMatch: [
        "**/stream.spec.ts",
        "**/integration.spec.ts",
        "**/profile.spec.ts",
        "**/sidebar.spec.ts",
        "**/sidebar-relay-card.spec.ts",
        "**/relay-restart.live.spec.ts",
        "**/parity-ancestor-island.spec.ts",
      ],
      use: {
        ...devices["Desktop Chrome"],
      },
      expect: {
        timeout: process.env.CI ? 15_000 : 10_000,
      },
    },
  ],
  webServer: {
    command: `python3 -m http.server ${port} -d ${process.env.BUZZ_E2E_DIST ?? "dist"}`,
    cwd: ".",
    reuseExistingServer: !process.env.CI,
    url: `http://127.0.0.1:${port}`,
  },
});
